namespace DXE_Utils.Models
{
    public class DDBPatBaseData
    {
        public int Id { get; set; }
        public string Id2 { get; set; }
        public string Title { get; set; }
        public string TitleFlg { get; set; }
        public string EzdwpAtid { get; set; }
        public string EmailAddress { get; set; }
        public string DriversLicense { get; set; }
        public string Fax { get; set; }
        public string Pager { get; set; }
        public string OtherPhone { get; set; }
        public string PrDed { get; set; }
        public string PrDed2 { get; set; }
        public string PrDed3 { get; set; }
        public string ScDed { get; set; }
        public string ScDed2 { get; set; }
        public string ScDed3 { get; set; }
        public string PrDeductLt { get; set; }
        public string PrDeductLt2 { get; set; }
        public string PrDeductLt3 { get; set; }
        public string ScDeductLt { get; set; }
        public string ScDeductLt2 { get; set; }
        public string ScDeductLt3 { get; set; }
        public string MedAlert { get; set; }
        public string FeeschId { get; set; }
        public string FeeschDb { get; set; }
        public string PrMedInsRel { get; set; }
        public string ScMedInsRel { get; set; }
        public string PrInsCdaDepCode { get; set; }
        public string ScInsCdaDepCode { get; set; }
        public string ConsultFlag { get; set; }
        public string ToaFlag { get; set; }
        public string DefaultClinic { get; set; }
        public string OperatorId { get; set; }
        public string OperatorDb { get; set; }
        public string UpLastName { get; set; }
        public string UpFirstName { get; set; }
        public string UpChart { get; set; }
        public string Active { get; set; }
        public string PatAlert { get; set; }
        public string Suffix { get; set; }
        public string CountyName { get; set; }
        public string EmpStatus { get; set; }
        public string Race { get; set; }
        public string FamIncome { get; set; }
        public string ExternalStatus { get; set; }
        public string PatExtId { get; set; }
        public string GuarantorExtId { get; set; }
        public string EntrySystem { get; set; }
        public DateTime EntryDateTime { get; set; }
        public string LastUpdateMethod { get; set; }
        public string LastUpdateSystem { get; set; }
        public string VisitNumber { get; set; }
        public string PatImageId { get; set; }
        public string InitProvId { get; set; }
        public string InitProvDb { get; set; }
        public string Religion { get; set; }
        public string RvUid { get; set; }
        public string RvUdb { get; set; }
        public DateTime MedHistoryViewDate { get; set; }
        public DateTime DdbLastMod { get; set; }
        public string PatClass { get; set; }
        public string PatFacility { get; set; }
        public string PatAliasLastName { get; set; }
        public string PatAliasFirstName { get; set; }
        public string PatAliasMiddleName { get; set; }
        public string PatAliasSuffix { get; set; }
        public string PatAliasPrefix { get; set; }
        public string MotherMaidenLName { get; set; }
        public string MotherMaidenFName { get; set; }
        public string MotherMaidenMName { get; set; }
        public string MotherMaidenSuffix { get; set; }
        public string MotherMaidenPrefix { get; set; }
        public DateTime PatientDeathDate { get; set; }
        public string Language { get; set; }
        public string PovertyLevel { get; set; }
        public string WorkerStatus { get; set; }
        public string HomelessStatus { get; set; }
        public string PrivacyFlags { get; set; }
        public string PatCopied { get; set; }
        public string TempChart { get; set; }
        public string Veteran { get; set; }
        public string GuidId { get; set; }
        public string TertDentInsuredId { get; set; }
        public string TertDentInsuredDb { get; set; }
        public string QuatDentInsuredId { get; set; }
        public string QuatDentInsuredDb { get; set; }
        public string TertInsRel { get; set; }
        public string QuatInsRel { get; set; }
        public string TertInsCdaDepCode { get; set; }
        public string QuatInsCdaDepCode { get; set; }
        public string OverrideUserId { get; set; }
        public string PermDescript { get; set; }
        public string EthnicityId { get; set; }
        public string UdPatCatId { get; set; }
        public string ExtPatIdType { get; set; }
        public string ExtGuarIdType { get; set; }
        public string PatExtId2 { get; set; }
        public string ExtPatId2Type { get; set; }
        public string PatType { get; set; }
        public string AccountStatus { get; set; }
        public string FinancialClassId { get; set; }
        public string PatAccountNumber { get; set; }
        public string DeclinedEmail { get; set; }
        public string CommunicationPref { get; set; }
        public string SmokingStatusId { get; set; }
        public string SmokingStatusDb { get; set; }
        public string RxAutoRefill { get; set; }
        public string OtherRace { get; set; }
        public string HousingStatus { get; set; }
        public string FamSize { get; set; }
        public string SexualOrientation { get; set; }
        public string GenderIdentity { get; set; }
        public string HohIncome { get; set; }
        public string IncomeRecurr { get; set; }
        public string PracticeIdInt { get; set; }
        public DateTime LastUpdateTimestamp { get; set; }
        public string IsDeletedFromSource { get; set; }
        public DateTime MinProcDateDi { get; set; }
        public DateTime MaxProcDateDi { get; set; }
        public DateTime LastPerioProcDi { get; set; }
        public DateTime LastHygieneProcDi { get; set; }
        public string PatientValue0To6 { get; set; }
        public string PatientValue7To12 { get; set; }
        public string PatientValue13To18 { get; set; }
        public string PatientValue19To24 { get; set; }
        public string PatientValue25To30 { get; set; }
        public string PatientValue31To36 { get; set; }
        public string UnScheduledTx { get; set; }
        public string TotalTx { get; set; }
        public DateTime NextHygieneAppt { get; set; }
        public DateTime NextNonHygieneAppt { get; set; }
        public DateTime StatusModifiedDate { get; set; }
        public DateTime HygieneIntervalDi { get; set; }
        public string PrimaryInsuranceDi { get; set; }
        public string SecondaryInsuranceDi { get; set; }
        public string RemainingInsuranceDi { get; set; }
        public DateTime FirstPerioProcDi { get; set; }
        public DateTime NextRestorativeAppointmentDi { get; set; }
        public DateTime NextMiscAppointmentDi { get; set; }
        public string RemainingPrimaryInsuranceDi { get; set; }
        public string RemainingSecondaryInsuranceDi { get; set; }
        public string Aging0To30Di { get; set; }
        public string Aging31To60Di { get; set; }
        public string Aging61To90Di { get; set; }
        public string AgingPlus90Di { get; set; }
        public string TotalAgingDi { get; set; }
        public string EstInsuranceAgingDi { get; set; }
        public string EstPatientAgingDi { get; set; }
        public string PrimaryProviderDi { get; set; }
        public string SecondaryProviderDi { get; set; }
        public string ReferralSourceDi { get; set; }
        public string NextHygieneApptIsOnQuickFillDi { get; set; }
        public string NextNonHygieneApptIsOnQuickFillDi { get; set; }
        public string NextRestorativeApptIsOnQuickFillDi { get; set; }
        public string NextMiscApptIsOnQuickFillDi { get; set; }
        public string FamilyMembersNotScheduledDi { get; set; }
        public string HygieneUnScheduledTxDi { get; set; }
        public string RestorativeUnScheduledTxDi { get; set; }
        public string AppointmentCandidateWeightingRestorativeDi { get; set; }
        public string AppointmentCandidateWeightingHygieneDi { get; set; }
        public DateTime NextHygieneApptEndTimeDi { get; set; }
        public DateTime NextNonHygieneApptEndTimeDi { get; set; }
        public DateTime NextRestorativeAppointmentEndTimeDi { get; set; }
        public DateTime NextMiscAppointmentEndTimeDi { get; set; }
        public string PatientIsOnUnscheduledQuickFill { get; set; }
        public string FupHygieneRecareChangedDi { get; set; }
        public string FupArChangedDi { get; set; }
        public DateTime LastMajorFilmProcDi { get; set; }
        public DateTime LastBiteWingProcDi { get; set; }
        public DateTime LastPanoProcDi { get; set; }
        public DateTime LastFmxProcDi { get; set; }
        public string UnScheduledTx0To30Di { get; set; }
        public string UnScheduledTx31To60Di { get; set; }
        public string UnScheduledTx61To90Di { get; set; }
        public string UnScheduledTxPlus90Di { get; set; }
        public string RestorativeUnScheduledTx0To30Di { get; set; }
        public string RestorativeUnScheduledTx31To60Di { get; set; }
        public string RestorativeUnScheduledTx61To90Di { get; set; }
        public string RestorativeUnScheduledTxPlus90Di { get; set; }
        public string HygieneUnScheduledTx0To30Di { get; set; }
        public string HygieneUnScheduledTx31To60Di { get; set; }
        public string HygieneUnScheduledTx61To90Di { get; set; }
        public string HygieneUnScheduledTxPlus90Di { get; set; }
    }

}
